delete merge branch (#12)

diff --git a/.github/workflows/delete-merged-branch.yaml b/.github/workflows/delete-merged-branch.yaml
--- a/.github/workflows/delete-merged-branch.yaml
+++ b/.github/workflows/delete-merged-branch.yaml
@@ -17,7 +17,14 @@ jobs:
           REPO: ${{ github.repository }}
         run: |
           echo "Deleting branch $BRANCH in repo $REPO"
-          curl -X DELETE \
+          response=$(curl -s -o response.txt -w "%{http_code}" -X DELETE \
             -H "Authorization: token $GITHUB_TOKEN" \
             -H "Accept: application/vnd.github+json" \
-            https://api.github.com/repos/$REPO/git/refs/heads/$BRANCH
+            https://api.github.com/repos/$REPO/git/refs/heads/$BRANCH)
+          echo "HTTP status code: $response"
+          echo "Response body:"
+          cat response.txt
+          if [ "$response" != "204" ]; then
+            echo "Failed to delete branch"
+            exit 1
+          fi
